[package]
name = "streamer-app"
version = "1.0.0"
authors = ["SionoiS <SionoiS@users.noreply.github.com>"]
edition = "2018"
licence = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["signal", "macros", "process", "rt-threaded", "sync"] }
ipfs-api = "0.8.0-rc.2"
cid = "*"
multibase = "*"
hyper = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"