[package]
name = "streamer-app"
version = "1.0.0"
authors = ["SionoiS <SionoiS@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["process", "macros"] }
ipfs-api = "0.7"
notify = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"