[package]
name = "web-app"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.17"
yew-router = "0.14"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde-wasm-bindgen = "0.1.3"
yewtil = "0.3"
web-sys = { version = "0.3", features = [
    "MediaSource",
    "MediaSourceReadyState",
    "SourceBuffer",
    "SourceBufferList",
    "Url",
    "HtmlMediaElement",
    "TimeRanges"
]}

