[package]
name = "web-app"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
m3u8-rs = "1.0"
cid = "0.5"
url = "2.1"

[dependencies.web-sys]
version = "0.3"
features = [ "HtmlMediaElement", "Document", "Element"
]