[package]
name = "web-app"
version = "0.1.0"
authors = ["SionoiS <SionoiS@users.noreply.github.com>"]
edition = "2018"
licence = "MIT OR Apache-2.0"

[dependencies]
yew = "0.17"
yew-router = "0.14"
wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
yewtil = "0.3"
cid = "0.6"
linked-data = { path = "../linked-data" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

web-sys = { version = "0.3", features = [
    "MediaSource",
    "MediaSourceReadyState",
    "SourceBuffer",
    "SourceBufferAppendMode",
    "Url",
    "HtmlMediaElement",
    "MediaError",
    "TimeRanges",
    "Performance",
    "Storage",
]}

