[package]
name = "web-app"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.17"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [ "Document", "Element", "HtmlElement", "Node", "Window" ] }
js-sys = "0.3"