[package]
name = "web-app"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.17"
yew-router = "0.14"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
m3u8-rs = "1.0"
cid = { version = "0.6", features = ["serde-codec"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
yewtil = "0.3"
web-sys = { version = "0.3", features = [
    "MediaSource",
    "MediaSourceReadyState",
    "SourceBuffer",
    "Url",
    "HtmlMediaElement"
]}

