[package]
name = "viewer-app"
version = "0.1.0"
authors = ["SionoiS <SionoiS@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
ipfs-api = "0.7"
hyper = "0.13"
cid = "0.5"
multihash = "0.11"
multibase = "0.8"