[package]
name = "linked-data"
version = "0.1.0"
authors = ["SionoiS <SionoiS@users.noreply.github.com>"]
edition = "2018"
licence = "MIT OR Apache-2.0"

[dependencies]
multihash = "0.13"
cid = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web3 = { version = "0.15", default-features = false, features = ["signing"] }